version: "3.0"
services:
  postgres:
    image: postgres:16.3-alpine
    container_name: postgres
    ports:
      - "5434:5434"
    command:
      - "postgres"
      - "-c"
      - "port=5434"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -p 5434 -d postgres -q"]
      interval: 3s
      timeout: 3s
      retries: 5

  app:
    image: app:test
    container_name: app
    ports:
      - "5000:5000"
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./src:/app/src