version: "3.0"
services:
  postgres:
    image: postgres:alpine
    container_name: postgres
    env_file:
      - .env
    ports:
      - "5434:5434"
    command:
      - "postgres"
      - "-c"
      - "port=5434"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -p 5434 -d postgres -q"]
      interval: 3s
      timeout: 3s
      retries: 5

  app:
    build: .
    env_file:
      - .env
    container_name: app
    ports:
      - "5000:5000"
    depends_on:
      postgres:
        condition: service_healthy
    command: alembic upgrade head
    restart: on-failure
    volumes:
      - ${STORAGE_PATH}:${DOCKER_PATH}
      - /Users/just_bsi/PycharmProjects/flask_app/src:/app/src